version: "3.9"
services:
  interface:
    build: ./interface
    ports:
      - "8080:8080"
    volumes:
      - ./interface:/app
    environment:
      - NODE_ENV=development
  servergo:
    build: ./server
    ports:
      - "8081:8080"
    volumes:
      - ./server:/app
    environment:
      - ENV=development
